site_name: 钒钒的赛博小屋 | Yifan's Homepage
theme:
  name: material

  icon:
    logo: material/github
    
  language: zh

  features:
    - navigation.tabs
    - navigation.top
    - search.highlight

copyright: Copyright @ 2025 Mr.J.Y.WU All Right Reserved



nav:
  - 首页:
    - 维护声明: 首页/维护声明.md
    - 关于钒钒: 首页/关于钒钒.md
  - 坡岛生活:
    - 吃在坡岛: 坡岛生活/吃在坡岛.md
    - 学在坡岛: 坡岛生活/学在坡岛.md
    - 轮上坡岛: 坡岛生活/轮上坡岛.md
  - 我与翼神:
    - 我与翼神: 我与翼神/我与翼神.md
    - 美图展示: 我与翼神/美图展示.md
  - 情感日记: 情感日记/情感日记.md
  

    